name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/free-disk-space
      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/ubuntu-dependencies

      - name: Run clippy
        run: |
          SKIP_WASM_BUILD=1 cargo clippy --all-targets --locked --workspace
        timeout-minutes: 99

      - name: Run the tests
        run: SKIP_WASM_BUILD=1 cargo test
        timeout-minutes: 99

      - name: Build the docs
        run: SKIP_WASM_BUILD=1 cargo doc --workspace --no-deps
        timeout-minutes: 15

  run-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/free-disk-space
      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/ubuntu-dependencies

      - name: Build the node individually in release mode
        run: cargo build --release
        timeout-minutes: 120

      - name: Make sure the node is producing blocks
        run: |
          ./target/release/xorion-node --dev 2>&1 | tee out.txt &
          until curl -s '127.0.0.1:9944'; do sleep 5; done
          until cat out.txt | grep -s "Imported #2"; do sleep 5; done
        shell: bash
        timeout-minutes: 5

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/free-disk-space

      - name: Build the Dockerfile
        run: docker build . -t xorion
        timeout-minutes: 90
