name: Scorecard analysis

on:
  pull_request:        # 🔥 Runs on PRs (so status is reported)
  push:
    branches: ["master"]  # or ["main"] if that's your default
  schedule:
    - cron: '30 1 * * 0'  # weekly run
  workflow_dispatch:

permissions:
  security-events: write
  id-token: write
  contents: read

jobs:
  analysis:
    name: Scorecard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          GITHUB_TOKEN: ${{ secrets.SCORECARD_TOKEN }}  # use your PAT

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

