name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: '30 1 * * 0' # weekly run
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OpenSSF Scorecard analysis
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.SCORECARD_TOKEN }}   # 👈 This is the difference!
        continue-on-error: true

      - name: Upload Scorecard results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

