name: Scorecard

on:
  push:
    branches: ["**"]       # Run on all branches
  pull_request:
    branches: ["**"]       # Run on all PRs
  schedule:
    - cron: '30 1 * * 0'   # Weekly run
  workflow_dispatch:       # Manual trigger

permissions:
  security-events: write
  id-token: write
  contents: read
  actions: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
        continue-on-error: true

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

